spring.data.mongodb.uri = mongodb://localhost:27017/invoicedb
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=a917d6001@smtp-brevo.com
spring.mail.password=xsmtpsib-dd318a29639c61c4863d3376305f550bbfd255381a98f907703f618e9d826272-8AqxqLTDTyinoOyM
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.from=shalinijagan952@gmail.com

clerk.issuer=https://modest-cougar-50.clerk.accounts.dev
clerk.jwks-url=https://modest-cougar-50.clerk.accounts.dev/.well-known/jwks.json